### ISSUE TITLE
No ‘projects’ directory when rake urbanopt_create_project

### ISSUE THREAD

**Issue by wannizhang** [urbanopt/urbanopt-prototype-district-generator#2]
Hi,
This is Wanni. I tried to test the repo, starting from creating a new project by the command, but it seems it requires a `projects` folder to exist in the current working directory.

> rake aborted!
Errno::ENOENT: No such file or directory @ dir_s_mkdir - projects/prototype_district_A

Is that by intention? Or do you want to use `FileUtils.mkdir_p` instead of `Dir.mkdir` in the rakefile?
```ruby
def create_project(json)
  folder_name = json.split(".")[0]
  dir_name = File.join(Dir.pwd, "projects/#{folder_name}")
  unless Dir.exists?(dir_name)
    Dir.mkdir File.join('projects', folder_name)
    Dir.mkdir File.join('projects', folder_name, 'weather')
    Dir.mkdir File.join('projects', folder_name, 'mappers')
```

**Comment by DavidGoldwasser** [comment]
Thanks!, fix is on https://github.com/urbanopt/urbanopt-prototype-district-generator/tree/weather_sweep, will merge to develop soon.
