### ISSUE TITLE
Fix typo in Rakefile

### ISSUE THREAD

**Issue by tanushree04** [urbanopt/urbanopt-prototype-district-generator#4]
Typo in https://github.com/urbanopt/urbanopt-prototype-district-templates/blob/weather_sweep/Rakefile#L179, should be .osw

**Comment by DavidGoldwasser** [comment]
@tanushree04 I haven't changed this yet but it seemed to run in current state/ I'm also wondering similar line just after should also chagne.
https://github.com/urbanopt/urbanopt-prototype-district-templates/blob/weather_sweep/Rakefile#L182
